# Generated by Django 5.0.4 on 2024-04-20 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('coffee_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='cafe.coffeehouse')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('size', models.IntegerField()),
                ('measure_unit', models.CharField(choices=[('г', 'Грамм'), ('кг', 'Килограмм'), ('мл', 'Миллилитр'), ('л', 'Литр')], max_length=2)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='menu.menu')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
