# Generated by Django 5.0.4 on 2024-04-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_rename_coffeehouses_coffeehouse'),
        ('menu', '0002_rename_menuitem_menuitems_rename_menu_menus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menus',
            new_name='Menu',
        ),
        migrations.RenameModel(
            old_name='MenuItems',
            new_name='MenuItem',
        ),
    ]
