# Generated by Django 5.0.4 on 2024-04-20 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_alter_coffeehouse_description'),
        ('menu', '0003_rename_menus_menu_rename_menuitems_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='coffee_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='cafe.coffeehouse'),
        ),
    ]
