# Generated by Django 5.0.4 on 2024-04-20 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_coffee_house'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name']},
        ),
    ]
