# Generated by Django 5.0.4 on 2024-04-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoffeeHouse',
            new_name='CoffeeHouses',
        ),
    ]
