# Generated by Django 5.0.4 on 2024-04-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_rename_coffeehouse_coffeehouses'),
        ('menu', '0002_rename_menuitem_menuitems_rename_menu_menus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoffeeHouses',
            new_name='CoffeeHouse',
        ),
    ]
