# Generated by Django 5.0.4 on 2024-04-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_rename_coffeehouses_coffeehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeehouse',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
